batch_size: 4
num_frames: 20
frame_size: 128
learning_rate: 0.0003
epochs: 8
cnn_output_dim: 256
lstm_hidden_size: 128
num_layers: 1
train_split: 0.8
raw_video_dir: data/raw_videos
frames_dir: data/frames
labels_csv: data/labels_subset.csv
